### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jpcarreon** [jpcarreon/Kunstzeal#1]
List of objectives that still needs to be done for the completion of the project.

- [x] Generate Spectrogram
- [x] Gather samples
- [x] Create the CNN model
- [x] Train the CNN model according to the samples
- [x] Develop a UI for the pre-trained model
- [x] Deploy App
- [x] Add documentation
- [x] Manuscript write-up
    - [x] Intro
    - [x] RRL
    - [x] Methodology
    - [x] Results
    - [x] Conclusion

## Miscellaneous Objectives
- [x] Accumulate at least 3000 samples
- [x] Optimize CNN accuracy
    - [x] 60%
    - [x] 90%
    - [x] 95%
- [ ] Add design to the UI
